# Site settings
title: Ethanify
description: Passionate about creating awesome products that help plenty of people improving their lives.
url: 'http://ethanify.me'
blog_url: 'http://dev.ethanify.me'
baseurl:

author:
  name: 'Ethan Nguyen'
  email: thanhnx.605@gmail.com
  twitter_username: ethan605
  facebook_username: ethan.605
  github_username: ethan605
  linkedin_username: ethan605

# Build settings
destination: _site
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
