name: Deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to surge.sh
    steps:
      - uses: actions/checkout@v1
      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install --production
      - run: npm run build
      - run: ./node_modules/.bin/surge ./build --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
