name: Deploy to surge.sh

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge.sh
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install --global surge
      - run: npm install
      - run: npm run build
      - run: surge ./build ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
