name: Production deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 18

      - name: Install and Build
        run: |
          npm install --omit=dev
          CI=false VITE_CANONICAL_URL=${{ secrets.PRODUCTION_DOMAIN }} npm run build --omit=dev

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: dist
          clean: true
