name: Production deployment

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install --production
      - run: npm audit
      - run: CI=false REACT_APP_CANONICAL_URL=${{ secrets.PRODUCTION_DOMAIN }} npm run build
      - run: ./node_modules/.bin/gh-pages -b master -d build
