name: Staging deployment

on: [pull_request]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 18

      - name: Install and Build
        run: |
          npm install --omit=dev --force
          CI=false REACT_APP_CANONICAL_URL=${{ secrets.SURGE_DOMAIN }} npm run build

      - name: Deploy
        run: |
          npm install -g surge
          surge build ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
