name: Staging deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          npm install --production
          CI=false REACT_APP_CANONICAL_URL=${{ secrets.SURGE_DOMAIN }} npm run build

      - name: Deploy
        uses: dswistowski/surge-sh-action@v1.0.1
        with:
          domain: ${{ secrets.SURGE_DOMAIN }}
          project: build
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
